theme: jekyll-theme-cayman
title: Face Landmark-based Speaker-Independent Audio-Visual Speech Enhancement in Multi-Talker Environments
description: Giovanni Morrone, Luca Pasa, Vadim Tikhanoff, Sonia Bergamaschi, Luciano Fadiga, Leonardo Badino <br> University of Modena and Reggio Emilia and Istituto Italiano di Tecnologia
repository: dr-pato/audio_visual_speech_enhancement
