theme: jekyll-theme-cayman
title: Audio-Visual Speech Inpainting with Deep Learning
description: Giovanni Morrone, Daniel Michelsanti, Zheng-Hua Tan, Jesper Jensen<br> University of Modena and Reggio Emilia and Aalborg University
repository: dr-pato/audio-visual-speech-inpainting
